### ISSUE TITLE
Не приходят данные в подписку при изменении State

### ISSUE THREAD

**Issue by infraymer** [Renesanse/osam#10]
Приветствую! При обновлении свойства `placeFrom` в `CreateOrderState` не получаю данные в `listen`. В случае со свойством `placesTo` при добавлении или удалении элементов списка `listen` срабатывает.

create_order_state.dart
```
class CreateOrderState extends BaseState<CreateOrderState> {

  Place placeFrom;

  List<Place> placesTo = [];

  var comment = Comment.empty();

  var price = 0;

  List<Place> get placesAll => [placeFrom] + placesTo;

  void swapPlacesTo(int first, int second) {
    var tmp = placesTo[first];
    placesTo.removeAt(first);
    placesTo.insert(second, tmp);
  }

  void updatePlaceFrom(Place place) {
    placeFrom = place;
  }

  @override
  List<Object> get props => [placeFrom, placesTo, comment, price];
}
```
main_presenter.dart
```
class MainPresenter<S extends Store<AppState>> extends Presenter<S> {

...
  StreamSubscription propertySub;
  StreamController<Place> _placeFromStreamController = StreamController.broadcast();

  @override
  void init() {
    propertySub = store.state.createOrderState
        .propertyStream<Place>((state) => state.placeFrom)
        .listen((data) {
      _placeFromStreamController.add(data);
    });
}

onPlaceFromSelected(Place place) {
    store.dispatchEvent(
        event: Event.modify(reducer: (state, _ ) => state.createOrderState..updatePlaceFrom(place))
    );
}
```

С чем это может быть связано? Нужно ли каким-то образом явно сообщать об изменении данных? Класс `Place` наследуется от `Equatable`.

**Comment by Renesanse** [comment]
Подозреваю, что стоит попробовать убрать наследование Place от Equatable

**Comment by infraymer** [comment]
@Renesanse, убрал, ситуация без изменений.

**Comment by Renesanse** [comment]
@infraymer какая версия библиотеки , Equatable. Пробовали pub get/upgrade?

**Comment by Renesanse** [comment]
Можно код Place посмотреть?

**Comment by Renesanse** [comment]
Итак, я еще раз проанализировал ваш код. Собственно вы слушаете изменение именно проперти, а нужно слушать изменение стейта. Суть в том, что вы не изменяете структуру проперти, а заменяете поле именно в стейте на другое. Если вы хотите слушать именно проперти, то нужно отнаследовать ваш плейс от BaseSate и написать методы внутри меняющие его, удачи ! =) p.s пишите лучше так 

```class MainPresenter extends Presenter<Store<AppState>>  ```

**Comment by Renesanse** [comment]
@infraymer если Place до и после идентичны, то изменения не придут

**Comment by infraymer** [comment]
@Renesanse, странно, но при прослушивании 'state' все равно при изменении `placeFrom` слушатель **не срабатывает**. Верно ли прослушиваю?
```
store.state.createOrderState.stateStream.listen((data) {
      _placeFromStreamController.add(data.placeFrom);
});
```

Класс `Place`
```
class Place {
  final Address address;
  final Point location;

  Place({this.address, this.location});
}

class Address {
  final String name;
  final String description;

  Address({this.name, this.description});
}
```

Новый `place` не равен текущему.

**Comment by infraymer** [comment]
Возможно ли без наследования от BaseState получать изменения проперти placeFrom? 06.12.2019, 20:35, "Daniel" <notifications@github.com>:@infraymer если Place до и после идентичны, то изменения не придут—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Renesanse** [comment]
@infraymer  изменил пример в репозитории где ваш кейс работает. Попробуйте сверить код. Для большей уверенности доменные элементы которые вы храните следует унаследовать или от BaseState или  Equatable. Не исключаю, что у вас могут использоваться старые зависимости, сверте версии на  pub.dev . Удаление папки .pub-cache позволит вам перезатянуть актуальные зависимости. За невозможностью воспроизвести, закрываю issue. Надеюсь у вас получится решить проблему, удачи! =)
